baseURL = "https://ngdinhtoan.github.io/"
languageCode = "en-us"
title = "Toán Nguyễn"

pygmentsStyle = "monokai"
pygmentsUseClasses = true

[params]
    description = "A personal site"
    author = "Toán Nguyễn"
