baseURL = "https://ngdinhtoan.github.io/"
languageCode = "en-us"
title = "Toán Nguyễn"

pygmentsStyle = "monokai"
pygmentsUseClasses = true

[params]
    description = "Developing with ♡"
    author = "Toán Nguyễn"
